[pytest]
# Enable python logging during tests, at info level by default
log_cli = True
log_cli_level = INFO

# Default options for pytest to use each execution
addopts =
    --ignore=tests_utils/
    --html=test-results/report.html
    --self-contained-html
    --json-report
    --json-report-file=test-results/results.json
    --json-report-omit=collectors
    --tracing=retain-on-failure
    --base-url=https://pat-qa.nonprod.pathways.nhs.uk
    # set for testing purposes, turn off slow mo when in a pipeline
    #--slowmo=350

# Allows pytest to identify the base of this project as the pythonpath
pythonpath = .

# These are the tags that pytest will recognise when using @pytest.mark
markers =
    utils: tests for utility classes provided by this blueprint
