name: "Run Playwright Tests"
runs-on: ubuntu-latest
timeout-minutes: 10

inputs:
  bcss_cloud_environment:
    description: "The environment to run against in lower case (e.g. bcss-1234)"
    required: true
    type: string
  marker_to_use:
    description: "The test marker to use when running tests (e.g. smoke)"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      shell: bash
      run: python -m playwright install --with-deps
    - name: Run specified tests
      shell: bash
      run: |
        URL_TO_USE="${URL_TO_USE_DEFAULT//<REPLACE>/${{ inputs.bcss_cloud_environment }}}"
        ORACLE_DB="${ORACLE_DB_DEFAULT//<REPLACE>/${{ inputs.bcss_cloud_environment }}}"
        pytest -m ${{ inputs.marker_to_use }} --base-url=https://$URL_TO_USE --ignore=tests_utils/
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: result-output-example
        path: test-results/
        retention-days: 3
