name: "Check axe-core version"
description: "Checks if our copy of axe-core is up to date"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create dependency update branch
        run: |
          git checkout -b axe-dependency-check
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install axe-core in temp dir
        run: |
          cd utils/resouces
          mkdir temp
          cd temp
          npm install axe-core
      - name: Retrieve axe.js file
        run: |
          cd node_modules/axe-core
          mv axe.js ../../../
      - name: Remove temp directory
        run: |
          cd ../../../
          rm -rf temp
      - name: Stage & commit file
        run: |
          git stage axe.js
          git diff-index --quiet HEAD || (git commit -a -m "axe.js scheduled update" --allow-empty)
      - name: Push changes to branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: axe-dependency-check
