name: Run Axe Dependency Check

on: [workflow_dispatch]

jobs:
  axe-dependency-check:
    name: "Axe Version Check"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          git checkout ${{ github.head_ref || github.ref_name }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install axe-core in temp dir
        run: |
          cd utils/resources
          mkdir temp
          cd temp
          npm install axe-core
      - name: Retrieve axe.js file
        run: |
          cd utils/resources/temp/node_modules/axe-core
          mv axe.js ../../../
      - name: Remove temp directory
        run: |
          cd utils/resources
          rm -rf temp
      - name: Commit to axe-dependency-check branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add utils/resources/axe.js
          git commit -m "axe-core automated update"
          git push
